# Generated by Django 5.2.7 on 2025-10-06 11:24

from django.db import migrations
from django.contrib.auth.models import User

def create_deleted_user(apps, schema_editor):
    User.objects.get_or_create(username='deleted_user', defaults={'password': '!'})


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_deleted_user),
    ]
