# Generated by Django 5.2.7 on 2025-10-06 12:01

import django.core.validators
import django.db.models.deletion
import movies.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20251006_1424'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000, message='Рецензия не может быть длиннее 5000 символов')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=movies.models.Comment.get_deleted_user, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000, message='Рецензия не может быть длиннее 5000 символов')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(default=movies.models.Review.get_deleted_user, on_delete=django.db.models.deletion.SET_DEFAULT, to='movies.author'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000, message='Рецензия не может быть длиннее 5000 символов')]),
        ),
    ]
