# Generated by Django 5.2.7 on 2025-10-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_comment_text_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
