# Generated by Django 5.2.7 on 2025-10-06 11:24

from django.db import migrations
from django.contrib.auth.models import User

def create_movie_categories(apps, schema_editor):
    Category = apps.get_model("movies", "Category")
    from movies.fixtures.db_test_data import CATEGORIES

    for name in CATEGORIES:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_year'),
    ]

    operations = [
        migrations.RunPython(create_movie_categories),
    ]
