# Generated by Django 5.2.7 on 2025-10-06 11:24

from django.db import migrations
from django.contrib.auth.models import User
import json

def create_movie_categories(apps, schema_editor):
    Category = apps.get_model("movies", "Category")
    with open('movies/fixtures/categories.json', 'r', encoding='utf-8') as f:
        CATEGORIES = json.loads(f.read())
    for name in CATEGORIES:
        Category.objects.get_or_create(name=name)
def remove_movie_categories(apps, schema_editor):
    Category = apps.get_model("movies", "Category")
    with open('movies/fixtures/categories.json', 'r', encoding='utf-8') as f:
        CATEGORIES = json.loads(f.read())
    Category.objects.filter(name__in=CATEGORIES).delete()

def create_authors(apps, schema_editor):
    Author = apps.get_model("movies", "Author")



class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_year'),
    ]

    operations = [
        migrations.RunPython(create_movie_categories, remove_movie_categories),
    ]
