# Generated by Django 5.2.7 on 2025-10-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20251008_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='image_photo/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('MV', 'Кинофильм'), ('SR', 'Сериал'), ('CR', 'Мультфильм')], max_length=2),
        ),
    ]
