# Generated by Django 5.2.7 on 2025-10-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_poster_alter_movie_genre_alter_movie_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
    ]
