# Generated by Django 5.2.7 on 2025-11-14 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_moviesubscriber_movie_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='movies.review'),
            preserve_default=False,
        ),
    ]
